# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160310_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='github_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
