# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_github_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='github_repos',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
