# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_github_repos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='github_repos',
        ),
    ]
