# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20160314_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepos',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos10',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos10_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos11',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos11_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos12',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos12_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos13',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos13_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos14',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos14_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos15',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos15_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos16',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos16_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos17',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos17_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos18',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos18_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos19',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos19_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos1_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos20',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos20_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos2_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos3_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos4_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos5_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos6_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos7',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos7_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos8',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos8_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos9',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github_repos9_hook',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GithubRepos',
        ),
    ]
