# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_reposstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_repos',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
