# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_account_current_repos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='current_repos',
            new_name='test_repos',
        ),
    ]
