# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20160424_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='github_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
