# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moleculeci', '0003_auto_20160226_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GithubInfo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github_name',
        ),
    ]
